# Site settings
title: "Carmoreno"
email: carlosandresmorenovelez@gmail.com
description: "Un espacio para compartir"
baseurl: ""
url: ""
title_description: "“Lo que sabemos es una gota, lo que desconocemos es todo un océano.” -Isaac Newton."
title_image: "images/avatar_5.jpeg"
google_analytics: "G-HRLCXJMSKH"
disqus_account: httpwwwcarmorenogithubio
github_repository: https://github.com/CarMoreno/carmoreno.github.io
addthis_id: "ra-55cd50d81668b6c5"
post_limit: 5

# Social usernames/URLs
twitter_username: SoyCarmoreno
github_username:  CarMoreno
codepen_username: CarMoreno
#duolingo_username: CarMoreno
linkedin_link: https://co.linkedin.com/in/carmoreno1
good_reads_link: https://www.goodreads.com/carmoreno
stackoverflow_link: https://stackoverflow.com/users/4508767/carlos-moreno?tab=profile

# Footer
# footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"
footer_left: "Blog personal de  <i class=\"fa fa-coffee\"></i> <a href=\"https://co.linkedin.com/in/carmoreno1\" target=\"_blank\">Carlos Andrés Moreno</a>"
footer_right: "<i> \"La belleza sin inteligencia es solamente geometría\"</i> <i class=\"fa fa-heart\"></i>"
# Build settings
markdown: kramdown
# highlighter: pygments
highlighter: rouge
kramdown:
  input: GFM
permalink: pretty
exclude: [vendor]
#Variables personales
keep_files: [about] #Mantener directorios y archivos
timezone: America/Bogota
# lang: es
